### ISSUE TITLE
FYI : env var override will be available for signupTargetLoginUrl

### ISSUE THREAD

**Issue by jfeng-salesforce** [SalesforceFoundation/simple-salesforce-dx-buildpack#9]
Hi SalesforceFoundation team,

Just wanted to give you a heads up about an upcoming change which will allow the signupTargetLoginUrl to be defined via an env var: https://github.com/forcedotcom/sfdx-core/pull/429

This is in case you would like to use the new env var instead of changing the project.json using a custom env var: https://github.com/SalesforceFoundation/simple-salesforce-dx-buildpack/pull/4 

(Please feel free to close this issue if you'd like to continue using your existing code, just wanted to let you know an "officially" supported path is coming down the pipeline :)  Thank you for your time!)

**Comment by davisagli** [comment]
@jfeng-salesforce Thanks, I appreciate the official support for this and the heads-up!

**Comment by jfeng-salesforce** [comment]
Hi @davisagli (and Salesforce Foundation team), the change is on the SFDX CLI version 7.111.4  (currently in `latest-rc` ).  With that (and future) versions, you'll have the option of using the `SFDX_SCRATCH_ORG_CREATION_LOGIN_URL` env variable to set or override `signupTargetLoginUrl` :) 

Hope you have a great weekend!
